### PR TITLE
fix: Don't shrink DAG beyond minimum size

### PR DESCRIPTION
**Pull request by matheus23**
Pretty much what it says on the tin.

The idea is to remember the minimum size configured for the DAG, and if removing verticies causes the count to fall below the minimum, then that's "as if the test failed", so we run `vertex_mask_tree.complicate()`, which tries to reduce it by less, until we either exhausted all options or found a version that's still above the minimum.

I added a proptest that checks whether an always-failing testcase causes the DAG to always end up at the configured minimum size.

### CODE REVIEW

**Comment by adaszko** [comment]
Hey.  Another nice contribution!  This is getting very specialised however.  I wonder if we could have two ways of generating and shrinking DAGs -- the smart one with all the shrinking logic smarts tailored for your needs, and a dumb one, i.e. the original "just generate a random bitmap and treat it as a DAG".  In my experience the dumb one is surprisingly effective (and simple).  Your strategy still has its place though.  I'm guessing you're interacting with a persistent storage or some other external requirements where reducing the number of vertices in shrinking breaks something for you?

The crucial observation substantiating the dumb approach is that even if you reduce the number of vertices in the shrinking process and thus trigger a different bug than the one that originally failed the test case, that different bug still needs to be fixed!  Once it's fixed, a re-run of the test would likely trigger the original bug anyway!  So in effect, the dumb approach is as effective as the smarter one!

**Comment by matheus23** [comment]
This broke something else for me: During shrinking, it would shrink to empty DAGs which couldn't be handled by my test at all.
Usually these empty DAGs wouldn't get generated at all (since I'd use `arb_dag(1..256, ...)`).
I'm thinking of this more like not breaking invariants. A similar check exists in [proptest's `vec` strategy](https://github.com/proptest-rs/proptest/blob/master/proptest/src/collection.rs#L621) to make sure it doesn't undershoot the minimum number of elements.

**Comment by matheus23** [comment]
I guess it's a different perspective: the test isn't *designed* to handle empty DAGs. It's not like it's a bug that it can't.

**Comment by adaszko** [comment]
I agree not all tests have to handle empty DAGs well.  However, wouldn't a simple `prop_assume!(!dag.is_empty())` solve it for you?

**Comment by matheus23** [comment]
TIL! I didn't know about `prop_assume!`.

However, given that it's common practice to respect size bounds during shrinking in other proptest strategies, what's your current thinking on merging this?

Another way to simplify the code would be to remove the lower bound (although I'm not sure, I've been using various lower bounds pretty happily recently...).

**Comment by adaszko** [comment]
> TIL! I didn't know about `prop_assume!`.
> 
> However, given that it's common practice to respect size bounds during shrinking in other proptest strategies, what's your current thinking on merging this?
> 
> Another way to simplify the code would be to remove the lower bound (although I'm not sure, I've been using various lower bounds pretty happily recently...).

I have no problem merging this but eventually, it'd be best to ship two separate mentioned strategies and document their differences in doc comments.

**Pull request merged**
